
//login Page
export const LOGIN_PROCESS_STARTED = "LOGIN_PROCESS_STARTED";
export const LOGIN_PROCESS_SUCCESS = "LOGIN_PROCESS_SUCCESS";
export const LOGIN_PROCESS_FAILED = "LOGIN_PROCESS_FAILED";


export const LOGIN_FORM_CHANGE = "LOGIN_FORM_CHANGE";




//register page 

export const REGISTER_PROCESS_STARTED = "REGISTER_PROCESS_STARTED";
export const REGISTER_PROCESS_SUCCESS = "REGISTER_PROCESS_SUCCESS";
export const REGISTER_PROCESS_FAILED = "REGISTER_PROCESS_FAILED";

export const REGISTER_FORM_CHANGE = "REGISTER_FORM_CHANGE";



//verify page

export const VERIFY_PROCESS_STARTED = "VERIFY_PROCESS_STARTED";
export const VERIFY_PROCESS_SUCCESS = "VERIFY_PROCESS_SUCCESS";
export const VERIFY_PROCESS_FAILED = "VERIFY_PROCESS_FAILED";

export const VERIFY_FORM_CHANGE = "VERIFY_FORM_CHANGE";



//forgot password


export const  FORGOT_PASSWORD_PROCESS_STARTED=" FORGOT_PASSWORD_PROCESS_STARTED";
export const FORGOT_PASSWORD_PROCESS_SUCCESS="FORGOT_PASSWORD_PROCESS_SUCCESS";
export const FORGOT_PASSWORD_PROCESS_FAILED="FORGOT_PASSWORD_PROCESS_FAILED";
export const FORGOT_PASSWORD_FORM_CHANGE="FORGOT_PASSWORD_FORM_CHANGE";

export const RESET_PASSWORD_PROCESS_STARTED="RESET_PASSWORD_PROCESS_STARTED";
export const RESET_PASSWORD_PROCESS_SUCCESS="FORGOT_PASSWORD_PROCESS_SUCCESS";
export const RESET_PASSWORD_PROCESS_FAILED="FORGOT_PASSWORD_PROCESS_FAILED";
export const RESET_PASSWORD_FORM_CHANGE="FORGOT_PASSWORD_FORM_CHANGE";

